const express = require('express')
const router = express.Router()
const ProductController = require('../Controllers/ProductController')

router.get('/create',ProductController.showform)
router.post('/create/insert',ProductController.insert)
router.post('/updatesp',ProductController.updatesp)
router.get('/update/:idsp',ProductController.showupdatesp)
router.get('/showsp/:page',ProductController.showlist)
router.get('/showcategories/:page',ProductController.showlistctgr)
router.get('/deletesp/:idsp',ProductController.deleteproduct)
router.get('/createctgr',ProductController.showformctgr)
router.post('/createctgr/insert',ProductController.insertctgr)
router.get('/updatectgr/:idctgr',ProductController.showupdatectgr)
router.post('/updatectgr',ProductController.updatectgr)
router.get('/deletectgr/:idctgr',ProductController.deletectgr)
router.post('/type',ProductController.type)
router.get('/findproduct',ProductController.findproduct)
router.get('/minproduct',ProductController.minproduct)
router.get('/maxproduct',ProductController.maxproduct)
router.get('/randomproduct',ProductController.randomproduct)
router.get('/newproduct',ProductController.newproduct)
router.get('/:page',ProductController.index)
router.use('/',ProductController.index)

module.exports = router
